### ISSUE TITLE
Acknowledgements

### ISSUE THREAD

**Issue by ktjaco** [Oslandia/osm-data-classification#8]
Hello,

I would like to say thank you for this amazing framework that has allowed me to assess contributor characteristics for part of my Master's thesis research. I am currently submitting a draft for publication and I was wondering if I could include thanks to the Oslandia team in the Acknowledgements sections of the paper? 

> Acknowledgments
Contributions from anyone who does not meet the criteria for authorship should be listed, with permission from the contributor, in an Acknowledgments section. 

https://onlinelibrary.wiley.com/page/journal/14679671/homepage/forauthors.html

Regards,
Kent

**Comment by ktjaco** [comment]
Response via email.

**Comment by garaud** [comment]
Hi @ktjaco !

Thank you very much for your message. It's great to have some feedbacks like yours.

Can you tell me more about the topic of your Master's thesis?

Hope your submission will be well accepted. If so, I would like to add the reference of your paper in the README of this project if you don't mind.

Regards,
Damien
